#!/usr/bin/env bash
# In this script we will transfer file to a remote server.

# ensure that the number of cli args provided is not less than 3 
if [[ $# -lt 3 ]]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

 path_file="$1"
 ip_address="$2"
 server_username="$3"
 ssh_key_path="$4"

 scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$path_file" "$server_username@$ip_address:~/"
