#!/usr/bin/env bash
# install nginx on my server ubuntu@3.90.85.212

sudo apt update
sudo apt upgrade -y

sudo apt install nginx -y

file_path="/var/www/your_domain/html/index.html"

sudo bash -c 'echo "Hello World!" > "$file_path"'
sudo service nginx restart

