#!/usr/bin/env bash
# In this script in addition to changing the contents of index.html
# we are also going to add another route /redirect_me

apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo systemctl restart nginx

