#!/usr/bin/env bash
# Install nginx on your web-01 server with the following configurations:
#+      Listens on port 80
#+      Returns the page containing "hello world" when queried at the root
# Configure /redirect_me as a "301 moved permanently"
# IInclude a custom 404 page containiing "Ceci n'est pas une page"
apt-get -y update
apt-get -y install nginx
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html

echo "Hello World!" > /etc/nginx/html/index.html
touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

printf %s "server{
    listen 80;
    listen [::]:80 default_server;
    root /etc/nginx/html;
    index index.html index.htm;
    location /redirect_me{
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
    location /404 {
        root /etc/nginx/html;
        internal;
    }

}" > /etc/nginx/sites-available/default

service nginx restart
