#!/usr/bin/env bash

# This script will connect to a server whose ip adrress is 100.26.10.144 and username is ubuntu

private_key=~/.ssh/school
user=ubuntu
server_address=100.26.10.144

ssh -i "$private_key" "$user@$server_address"
